spring:
  application:
    name: training-grounds
  cloud:
    services:
      registrationMethod: route
      
---
spring:  
  profiles: jiu-jitsu
dojo:
  discipline: bjj
---
spring:  
  profiles: judo
dojo:
  discipline: judo  