spring:
  application:
    name: training-grounds
  cloud:
    services:
      registrationMethod: route
spring:
  jpa:
    hibernate:
      ddl-auto: create      

---
spring:  
  profiles: jiu-jitsu
dojo:
  discipline: bjj
---
spring:  
  profiles: judo
dojo:
  discipline: judo  